@ECHO OFF
ECHO Starting Powershell script...
PowerShell.exe -NoExit -NoProfile -Command "& {Start-Process PowerShell.exe -ArgumentList '-Windowstyle Maximized -NoExit -NoProfile -ExecutionPolicy Bypass -File ""%~dpn0.ps1""' -Verb RunAs}"
